### ISSUE TITLE
[Bug] `prettier . --write` does not run on .gjs/.gts files

### ISSUE THREAD

**Issue by simonihmig** [gitKrystan/prettier-plugin-ember-template-tag#113]
### 🐞 Describe the Bug

`prettier . --write` does not run on .gjs/.gts files

### 🔬 Minimal Reproduction

I run `prettier . --write`

### 😕 Actual Behavior

It reformats all files, except for .gjs/.gts files. CLI output list all kind of files, like .js/.cjs/.mjs, but no .gjs/.gts

### 🤔 Expected Behavior

Should reformat  .gjs/.gts files. 

### 🌍 Environment

- prettier-plugin-ember-template-tag version: 1.0.2
- ember-template-imports version: -

### ➕ Additional Context

When I run `prettier path/to/component.gts --write` then it does work! Also running prettier using VSCode does work correctly. So it seem only `prettier .` seems to ignore any .gjs/.gts files

**Comment by fdeters** [comment]
I've reproduced this issue, and found that it _does_ work when specifying a file, like `npx prettier --write app/components/my-component.gjs`, but doesn't work with directories, like `npx prettier --write app/components`.

**Comment by NullVoxPopuli** [comment]
My prettier command is now:
```
prettier -c "**/*.{js,gjs,cjs,mjs,json,hbs,ts,cts,mts,gts}"
```
:sweat_smile: 

My changes: https://github.com/NullVoxPopuli/limber/pull/1312/commits/80433f77df98d4cc46c93f26110e1fb35c4ab50e#diff-fcf5729f4474308f357cea6ec1123607ce116df8a7a60516595fac5f5327e01bR33

**Comment by gitKrystan** [comment]
Sorry for the annoying bug. :-(

Based on Prettier's documentation, `prettier --write .` _should_ be working, but it seems like we actually need to do `prettier --write --plugin prettier-plugin-ember-template-tag`. I am finding other plugins using this hack too but no one seems to mention it's a hack?

I will update the documentation accordingly and open an issue on `prettier`.

**Comment by gitKrystan** [comment]
https://github.com/prettier/prettier/issues/15351

**Comment by gitKrystan** [comment]
Looks like this bug was introduced in prettier v3 and there is a fix in the works. More info at https://github.com/prettier/prettier/issues/15079

In the meantime at the plugin flag as I mentioned above.

**Comment by bartocc** [comment]
Like @NullVoxPopuli commented on discord, prettier@3.1 has been released this WE 🎉

**Comment by gitKrystan** [comment]
README updated. I will re-open this if it's still borked.
