### ISSUE TITLE
RFC: `<template>` in `CallExpression` argument position

### ISSUE THREAD

**Issue by gitKrystan** [gitKrystan/prettier-plugin-ember-template-tag#192]
Vote by reacting to this issue. Comment with more details below. Do you prefer:

## Option A (🚀)

This is what v2.0.0-0 is currently returning.

```js
await render(
  <template>
    <h1>I am a multi-line template</h1>
    <p>With some text</p>
  </template>,
);
```

## Option B (👎)

This is what v1 currently returns.

```js
await render(<template>
  <h1>I am a multi-line template</h1>
  <p>With some text</p>
</template>);
```

**Comment by NullVoxPopuli** [comment]
I always format my own stuff as the option a anyway. I think it looks better
