### ISSUE TITLE
RFC: Short templates in the top-level-of-a-class position

### ISSUE THREAD

**Issue by gitKrystan** [gitKrystan/prettier-plugin-ember-template-tag#193]
Vote by reacting to this issue. Comment with more details below. Do you prefer:

## Option A (🚀)

This is what v2.0.0-0 is currently returning.

```js
export default class MyComponent extends Component {
  <template>Hey shorty</template>
}
```

## Option B (👎)

This is what v1 currently returns.

```js
export default class MyComponent extends Component {
  <template>
    Hey shorty
  </template>
}
```

## Caveats

Neither of these solutions address the issue that whitespace matters in html. 🙈 I haven't had any issues reported here about whitespace causing issues so I am choosing to ignore that for now.

**Comment by NullVoxPopuli** [comment]
Option A, less text nodes.
Also, very few templates will be one line

**Comment by IgnaceMaes** [comment]
Relevant RFC looking to address the whitespace difference: https://github.com/emberjs/rfcs/issues/982

As mentioned by @NullVoxPopuli, would this imply a template with a single element would also be on one line as follows?

```js
export default class MyComponent extends Component {
  <template><h1>Hey shorty</h1></template>
}
```

Or would it then switch to a new line?

```js
export default class MyComponent extends Component {
  <template>
    <h1>Hey shorty</h1>
  </template>
}
```

Because for that case I also would prefer option b.

**Comment by gitKrystan** [comment]
> As mentioned by @NullVoxPopuli, would this imply a template with a single element would also be on one line as follows?

In the current implementation, yes.

**Comment by NullVoxPopuli** [comment]
oh, I'd prefer the link breaks then

**Comment by gossi** [comment]
trying v2 right now, which is producing one-liners _with_ html tags is not giving the visual cue for the template I'm trying to find.

the short version is nice for tests though 😇

**Comment by gitKrystan** [comment]
Update:

I got this working, which is how the JSX formatter works:

One line if there is no tag:
```
<template>Hey shorty</template>
```

Multi lines if there is a tag:
```
<template>
  <h1>Hey shorty</h1>
</template>
```

Multi lines if there is a block:
```
<template>
  {{#if true}}
    Hey shorty
   {{/if}}
</template>
```

One line in this case too:
```
<template>{{if true 'Hey shorty'}}</template>
```
