### ISSUE TITLE
Usage of only-allow

### ISSUE THREAD

**Issue by chrisrng** [gitKrystan/prettier-plugin-ember-template-tag#90]
In the preinstall script we use `only-allow` which is not a dependency of this project.
Can we move this off preinstall for cases where we cannot use npx?

```
"preinstall": "npx only-allow pnpm",
```
See https://github.com/gitKrystan/prettier-plugin-ember-template-tag/blob/main/package.json#L36

**Comment by chriskrycho** [comment]
IIUC from chatting with @chrisrng, the issue here is that `npx` wants internet access, and many CI boxen don't have it. We should either make it a dev dependency *or* put this in some other script.

**Comment by chrisrng** [comment]
Unfortunately we're still hit by the issue with 1.0.1
